# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jean-François Collin
#
# Mirror of pattern_jass/src/pattern.hpp (v4 — enriched geometry).
# 40 patterns × 12 squares, ternary encoding, 21 257 640 buckets total.

import numpy as np

# Generated by gen_patterns.py --emit (single source of truth — do not edit by
# hand; v4 enriched geometry, mirrors pattern.hpp).
PATTERNS: list[list[int]] = [
# @GEN-PATTERNS-BEGIN
    [ 1,  2,  6,  7, 11, 12, 16, 17, 21, 22, 26, 27],   # v_top_0
    [ 2,  3,  7,  8, 12, 13, 17, 18, 22, 23, 27, 28],   # v_top_1
    [ 3,  4,  8,  9, 13, 14, 18, 19, 23, 24, 28, 29],   # v_top_2
    [ 4,  5,  9, 10, 14, 15, 19, 20, 24, 25, 29, 30],   # v_top_3
    [21, 22, 26, 27, 31, 32, 36, 37, 41, 42, 46, 47],   # v_bot_0
    [22, 23, 27, 28, 32, 33, 37, 38, 42, 43, 47, 48],   # v_bot_1
    [23, 24, 28, 29, 33, 34, 38, 39, 43, 44, 48, 49],   # v_bot_2
    [24, 25, 29, 30, 34, 35, 39, 40, 44, 45, 49, 50],   # v_bot_3
    [ 1,  2,  7,  8, 12, 13, 18, 19, 23, 24, 29, 30],   # diag_0
    [ 6,  7, 11, 12, 17, 18, 22, 23, 28, 29, 33, 34],   # diag_1
    [ 7,  8, 12, 13, 18, 19, 23, 24, 29, 30, 34, 35],   # diag_2
    [11, 12, 17, 18, 22, 23, 28, 29, 33, 34, 39, 40],   # diag_3
    [16, 17, 21, 22, 27, 28, 32, 33, 38, 39, 43, 44],   # diag_4
    [17, 18, 22, 23, 28, 29, 33, 34, 39, 40, 44, 45],   # diag_5
    [21, 22, 27, 28, 32, 33, 38, 39, 43, 44, 49, 50],   # diag_6
    [ 3,  4,  8,  9, 12, 13, 17, 18, 21, 22, 26, 27],   # anti_0
    [ 4,  5,  9, 10, 13, 14, 18, 19, 22, 23, 27, 28],   # anti_1
    [ 9, 10, 13, 14, 18, 19, 22, 23, 27, 28, 31, 32],   # anti_2
    [13, 14, 18, 19, 22, 23, 27, 28, 31, 32, 36, 37],   # anti_3
    [14, 15, 19, 20, 23, 24, 28, 29, 32, 33, 37, 38],   # anti_4
    [19, 20, 23, 24, 28, 29, 32, 33, 37, 38, 41, 42],   # anti_5
    [23, 24, 28, 29, 32, 33, 37, 38, 41, 42, 46, 47],   # anti_6
    [24, 25, 29, 30, 33, 34, 38, 39, 42, 43, 47, 48],   # anti_7
    [ 1,  2,  3,  4,  6,  7,  8,  9, 11, 12, 13, 14],   # horiz_0
    [12, 13, 14, 15, 17, 18, 19, 20, 22, 23, 24, 25],   # horiz_1
    [21, 22, 23, 24, 26, 27, 28, 29, 31, 32, 33, 34],   # horiz_2
    [27, 28, 29, 30, 32, 33, 34, 35, 37, 38, 39, 40],   # horiz_3
    [36, 37, 38, 39, 41, 42, 43, 44, 46, 47, 48, 49],   # horiz_4
    [ 2,  3,  4,  7,  8,  9, 12, 13, 14, 17, 18, 19],   # sq_0
    [16, 17, 18, 21, 22, 23, 26, 27, 28, 31, 32, 33],   # sq_1
    [18, 19, 20, 23, 24, 25, 28, 29, 30, 33, 34, 35],   # sq_2
    [32, 33, 34, 37, 38, 39, 42, 43, 44, 47, 48, 49],   # sq_3
    [ 1,  2,  3,  7,  8,  9, 12, 13, 14, 18, 19, 20],   # db_0
    [ 7,  8,  9, 12, 13, 14, 18, 19, 20, 23, 24, 25],   # db_1
    [17, 18, 19, 22, 23, 24, 28, 29, 30, 33, 34, 35],   # db_2
    [26, 27, 28, 31, 32, 33, 37, 38, 39, 42, 43, 44],   # db_3
    [ 2,  3,  4,  7,  8,  9, 11, 12, 13, 16, 17, 18],   # ab_0
    [ 8,  9, 10, 12, 13, 14, 17, 18, 19, 21, 22, 23],   # ab_1
    [18, 19, 20, 22, 23, 24, 27, 28, 29, 31, 32, 33],   # ab_2
    [28, 29, 30, 32, 33, 34, 37, 38, 39, 41, 42, 43],   # ab_3
# @GEN-PATTERNS-END
]

# @GEN-NAMES-BEGIN
PATTERN_NAMES = ["v_top_0", "v_top_1", "v_top_2", "v_top_3", "v_bot_0", "v_bot_1", "v_bot_2", "v_bot_3", "diag_0", "diag_1", "diag_2", "diag_3", "diag_4", "diag_5", "diag_6", "anti_0", "anti_1", "anti_2", "anti_3", "anti_4", "anti_5", "anti_6", "anti_7", "horiz_0", "horiz_1", "horiz_2", "horiz_3", "horiz_4", "sq_0", "sq_1", "sq_2", "sq_3", "db_0", "db_1", "db_2", "db_3", "ab_0", "ab_1", "ab_2", "ab_3"]
# @GEN-NAMES-END

NUM_PATTERNS         = len(PATTERNS)               # 40
PATTERN_SIZE         = 12
BUCKETS_PER_PATTERN  = 3 ** PATTERN_SIZE           # 531 441
TOTAL_BUCKETS        = BUCKETS_PER_PATTERN * NUM_PATTERNS  # 21 257 640

POW3 = np.array([3 ** k for k in range(PATTERN_SIZE + 1)], dtype=np.int64)
PATTERN_OFFSETS = np.arange(NUM_PATTERNS, dtype=np.int64) * BUCKETS_PER_PATTERN


def extract_indices(black_men: np.ndarray, white_men: np.ndarray) -> np.ndarray:
    n = len(black_men)
    out = np.zeros((n, NUM_PATTERNS), dtype=np.int64)
    for pi, sqs in enumerate(PATTERNS):
        idx = np.zeros(n, dtype=np.int64)
        for k, sq in enumerate(sqs):
            bit = np.uint64(1) << np.uint64(sq - 1)
            is_black = ((black_men & bit) != 0).astype(np.int64)
            is_white = ((white_men & bit) != 0).astype(np.int64)
            cell = is_black * 1 + is_white * 2
            idx += cell * int(POW3[k])
        out[:, pi] = idx
    return out


def flat_feature_columns(indices: np.ndarray) -> np.ndarray:
    return indices + PATTERN_OFFSETS[np.newaxis, :]
