# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jean-François Collin
#
# Mirror of pattern_jass/src/pattern.hpp (v4 — enriched geometry).
# 32 patterns × 12 squares, ternary encoding, 17 006 112 buckets total.

import numpy as np

# Generated by gen_patterns.py --emit (single source of truth — do not edit by
# hand; v4 enriched geometry, mirrors pattern.hpp).
PATTERNS: list[list[int]] = [
# @GEN-PATTERNS-BEGIN
    [ 1,  2,  6,  7, 11, 12, 16, 17, 21, 22, 26, 27],   # v_top_0
    [ 2,  3,  7,  8, 12, 13, 17, 18, 22, 23, 27, 28],   # v_top_1
    [ 3,  4,  8,  9, 13, 14, 18, 19, 23, 24, 28, 29],   # v_top_2
    [ 4,  5,  9, 10, 14, 15, 19, 20, 24, 25, 29, 30],   # v_top_3
    [21, 22, 26, 27, 31, 32, 36, 37, 41, 42, 46, 47],   # v_bot_0
    [22, 23, 27, 28, 32, 33, 37, 38, 42, 43, 47, 48],   # v_bot_1
    [23, 24, 28, 29, 33, 34, 38, 39, 43, 44, 48, 49],   # v_bot_2
    [24, 25, 29, 30, 34, 35, 39, 40, 44, 45, 49, 50],   # v_bot_3
# @GEN-PATTERNS-END
]

# @GEN-NAMES-BEGIN
PATTERN_NAMES = ["v_top_0", "v_top_1", "v_top_2", "v_top_3", "v_bot_0", "v_bot_1", "v_bot_2", "v_bot_3"]
# @GEN-NAMES-END

NUM_PATTERNS         = len(PATTERNS)               # 32
PATTERN_SIZE         = 12
# Bucket hashing (must match src/pattern.hpp PATTERN_HASH) : the full base-3
# index is reduced mod PATTERN_HASH at the lookup. Default = 3**SIZE → no-op.
PATTERN_HASH         = 3 ** PATTERN_SIZE           # 531 441 → no hashing
BUCKETS_PER_PATTERN  = PATTERN_HASH
TOTAL_BUCKETS        = BUCKETS_PER_PATTERN * NUM_PATTERNS  # 17 006 112

POW3 = np.array([3 ** k for k in range(PATTERN_SIZE + 1)], dtype=np.int64)
PATTERN_OFFSETS = np.arange(NUM_PATTERNS, dtype=np.int64) * BUCKETS_PER_PATTERN


def extract_indices(black_men: np.ndarray, white_men: np.ndarray) -> np.ndarray:
    n = len(black_men)
    out = np.zeros((n, NUM_PATTERNS), dtype=np.int64)
    for pi, sqs in enumerate(PATTERNS):
        idx = np.zeros(n, dtype=np.int64)
        for k, sq in enumerate(sqs):
            bit = np.uint64(1) << np.uint64(sq - 1)
            is_black = ((black_men & bit) != 0).astype(np.int64)
            is_white = ((white_men & bit) != 0).astype(np.int64)
            cell = is_black * 1 + is_white * 2
            idx += cell * int(POW3[k])
        out[:, pi] = idx
    return out


def flat_feature_columns(indices: np.ndarray) -> np.ndarray:
    return (indices % PATTERN_HASH) + PATTERN_OFFSETS[np.newaxis, :]
