// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Jean-François Collin
//
// Pattern feature extraction for jass (50-square draughts).
//
// v4 (ENRICHED geometry) : 32 patterns × 12 squares, ternary encoding.
// Generated by pattern_jass/tools/gen_patterns.py (single source of truth) —
// run `gen_patterns.py --emit` to regenerate the PATTERNS array below and the
// patterns.py mirror together. v3 had 8 VERTICAL bands only; v4 adds the
// orientations a draughts board actually uses: true physical DIAGONALS (both
// directions), HORIZONTAL advancement blocks, and compact SQUARE blocks, so
// the additive pattern class can fit structures the vertical-only set missed.
// The 8 v3 vertical bands are kept verbatim as the first 8 (strict superset).
//
// Conventions :
//   * Bit `i` of the uint64 bitboard = FMJD square (i+1)
//   * Cell encoding : 0 = empty, 1 = black_man, 2 = white_man
//   * Kings are NOT in patterns (matches Scan §3)
//   * Index : sum(cell[squares[i]] * 3^i) for i in [0, size)

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace pattern_jass {

using Bitboard = std::uint64_t;
using Square   = std::uint8_t;   // FMJD 1..50

constexpr std::size_t PATTERN_SIZE  = 12;
constexpr std::size_t NUM_PATTERNS  = 8;   // v4 enriched (gen_patterns.py)

struct Pattern {
    std::array<Square, PATTERN_SIZE> squares;
    std::string_view name;
};

constexpr std::array<std::uint32_t, PATTERN_SIZE + 1> POW3 = {
    1, 3, 9, 27, 81, 243, 729, 2187, 6561, 19683, 59049, 177147, 531441,
};

// Bucket hashing (piste 3 / data-efficiency) : extract_all still yields the full
// base-3 index (0 .. POW3[SIZE]-1), but the table lookup reduces it mod
// PATTERN_HASH, so each pattern's weight table has PATTERN_HASH entries. Default
// = POW3[SIZE] → the mod is a NO-OP (identical to the un-hashed eval). A smaller
// PATTERN_HASH fights data-starvation : far fewer, far better-trained buckets
// (stable at depth) — the rare configs that gave garbage at depth get pooled
// with common ones (regularised) instead of staying under-trained, at the cost
// of hash collisions. The trainer (patterns.py) MUST use the same PATTERN_HASH.
constexpr std::uint32_t PATTERN_HASH        = 531441;   // = POW3[12] → no hashing
constexpr std::uint32_t BUCKETS_PER_PATTERN = PATTERN_HASH;
constexpr std::uint32_t TOTAL_BUCKETS       = BUCKETS_PER_PATTERN * NUM_PATTERNS;

// 32 patterns of 12 squares (v4). Generated by gen_patterns.py --emit.
// Order: 8 vertical bands (v3, verbatim), 7 down-right diagonals, 8
// anti-diagonals, 5 horizontal 3×4 blocks, 4 compact 4×3 square blocks.
inline constexpr std::array<Pattern, NUM_PATTERNS> PATTERNS = {{
// @GEN-PATTERNS-BEGIN
    {{ 1,  2,  6,  7, 11, 12, 16, 17, 21, 22, 26, 27}, "v_top_0"},
    {{ 2,  3,  7,  8, 12, 13, 17, 18, 22, 23, 27, 28}, "v_top_1"},
    {{ 3,  4,  8,  9, 13, 14, 18, 19, 23, 24, 28, 29}, "v_top_2"},
    {{ 4,  5,  9, 10, 14, 15, 19, 20, 24, 25, 29, 30}, "v_top_3"},
    {{21, 22, 26, 27, 31, 32, 36, 37, 41, 42, 46, 47}, "v_bot_0"},
    {{22, 23, 27, 28, 32, 33, 37, 38, 42, 43, 47, 48}, "v_bot_1"},
    {{23, 24, 28, 29, 33, 34, 38, 39, 43, 44, 48, 49}, "v_bot_2"},
    {{24, 25, 29, 30, 34, 35, 39, 40, 44, 45, 49, 50}, "v_bot_3"},
// @GEN-PATTERNS-END
}};

constexpr std::array<std::uint32_t, NUM_PATTERNS> pattern_offsets() noexcept {
    std::array<std::uint32_t, NUM_PATTERNS> out{};
    for (std::size_t i = 0; i < NUM_PATTERNS; ++i) {
        out[i] = static_cast<std::uint32_t>(i * BUCKETS_PER_PATTERN);
    }
    return out;
}

std::uint32_t extract_index(Bitboard black_men, Bitboard white_men,
                            const Pattern& p) noexcept;

void extract_all(Bitboard black_men, Bitboard white_men,
                 std::array<std::uint32_t, NUM_PATTERNS>& out) noexcept;

// Incremental update : given the per-pattern base-3 indices `idx` valid for the
// BEFORE men-bitboards, update them in place to the AFTER men-bitboards. Only
// patterns containing a square whose men-occupancy changed are touched (via a
// precomputed reverse map square→{(pattern,pos)}). Equivalent to, but much
// cheaper than, a full extract_all when few squares change (a move touches ≤4).
// Kings are not in patterns, so only men bitboards matter.
void update_all(Bitboard bm_before, Bitboard wm_before,
                Bitboard bm_after,  Bitboard wm_after,
                std::array<std::uint32_t, NUM_PATTERNS>& idx) noexcept;

}  // namespace pattern_jass
