#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Jean-François Collin
"""Build a master-game-frequency opening book.

Walks `expert_games.db`, replays each game through jass to collect
`(FEN, move)` pairs from the first --max-plies plies. Aggregates per
position; the most-played master move is kept when at least
--min-count games visited the position.

Output: a TSV file (one `FEN<TAB>move` per kept position) suitable for
`jass --build-book-from-moves`. That C++ side computes the Zobrist
hash and packs the move into the binary JBOK format jass actually
loads at runtime via `--book`.

Design notes:
  * We do NOT call jass's search here — the v1 book is pure
    master-frequency. v2 (hybrid) will add a separate validation pass
    via `tools/build_master_book.py --validate-with-engine`.
  * Replay uses the same `JassOracle` HUB driver as pdn_to_jnnw.py;
    moves are HUB notation (`32-28`, `27x18`, ...). PDN tournament
    PDN bodies use the same notation so apply() takes them as-is.
  * Position de-dup is done by FEN string (engine-canonical), not by
    bitboard tuple — JassOracle's `fen` command emits jass's own FEN
    so `--build-book-from-moves` parses them losslessly.
"""
from __future__ import annotations

import argparse
import logging
import sqlite3
import sys
from collections import Counter, defaultdict
from pathlib import Path

# Reuse PDN parsing + oracle driver from the JNNW pipeline.
sys.path.insert(0, str(Path(__file__).parent))
from pdn_to_jnnw import (  # noqa: E402
    JassOracle,
    _strip_tags_and_comments,
    extract_moves,
)


def _aggregate(games, oracle: JassOracle, max_plies: int,
               log: logging.Logger):
    """Walk games, return dict[fen -> Counter(move -> n_occurrences)]."""
    position_moves: dict[str, Counter] = defaultdict(Counter)
    ok = 0
    rejected = 0
    for i, (pdn, _wr, _br, _res) in enumerate(games):
        body = _strip_tags_and_comments(pdn)
        moves = extract_moves(body)
        if not moves:
            rejected += 1
            continue
        try:
            oracle.reset()
        except RuntimeError as e:
            log.error(f"oracle reset failed: {e}")
            rejected += 1
            continue
        game_ok = True
        for ply, mv in enumerate(moves):
            if ply >= max_plies:
                break
            try:
                fen = oracle.fen()
            except RuntimeError as e:
                log.warning(f"game {i}: fen failed at ply {ply}: {e}")
                game_ok = False
                break
            position_moves[fen][mv] += 1
            if not oracle.apply(mv):
                # Move rejected — likely a notation we don't parse. The
                # (fen, move) we already recorded above is still valid;
                # we just stop early on this game.
                # Pop the last entry we added since we didn't actually
                # play it through; without that, we'd record a move
                # jass can't replay.
                position_moves[fen][mv] -= 1
                if position_moves[fen][mv] <= 0:
                    del position_moves[fen][mv]
                    if not position_moves[fen]:
                        del position_moves[fen]
                game_ok = False
                break
        if game_ok:
            ok += 1
        if (i + 1) % 500 == 0:
            log.info(
                f"  processed {i+1}/{len(games)} games, "
                f"unique positions={len(position_moves)}, "
                f"ok={ok} rejected={rejected}")
    log.info(f"replay done: {ok} ok, {rejected} rejected, "
             f"{len(position_moves)} unique positions")
    return position_moves


def _emit(position_moves, out_path: Path, min_count: int,
          min_rating: int, max_plies: int, log: logging.Logger) -> int:
    n_kept = 0
    n_filtered = 0
    with out_path.open("w") as out:
        out.write("# Generated by build_master_book.py\n")
        out.write(
            f"# rating_min={min_rating} max_plies={max_plies} "
            f"min_count={min_count}\n")
        for fen, moves in position_moves.items():
            total = sum(moves.values())
            if total < min_count:
                n_filtered += 1
                continue
            # Most-played master move; ties broken by Counter's insertion
            # order (i.e. first seen wins).
            best_move, _best_count = moves.most_common(1)[0]
            out.write(f"{fen}\t{best_move}\n")
            n_kept += 1
    log.info(f"wrote {n_kept} entries to {out_path} "
             f"(filtered {n_filtered} below min_count={min_count})")
    return n_kept


def main(argv: list[str]) -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--db", required=True,
                   help="path to expert_games.db (SQLite)")
    p.add_argument("--jass", required=True,
                   help="path to the jass binary (drives the FEN/apply oracle)")
    p.add_argument("--out", required=True,
                   help="output TSV with `FEN<TAB>move` per line")
    p.add_argument("--min-rating", type=int, default=2000,
                   help="keep games where either side is rated >= this")
    p.add_argument("--max-plies", type=int, default=16,
                   help="extract (fen, move) pairs only for plies < this")
    p.add_argument("--min-count", type=int, default=3,
                   help="emit only positions reached by >= this many games")
    p.add_argument("--limit", type=int, default=0,
                   help="cap on games to process (0 = no cap)")
    args = p.parse_args(argv)

    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s build_master_book | %(message)s")
    log = logging.getLogger("build_master_book")

    conn = sqlite3.connect(args.db)
    q = (
        "SELECT pdn, white_rating, black_rating, result "
        "FROM expert_games "
        "WHERE variant = 'standard' "
        "AND result IN ('1-0','0-1','1/2-1/2') "
        "AND (white_rating >= ? OR black_rating >= ?) "
        "ORDER BY id"
    )
    if args.limit > 0:
        q += f" LIMIT {args.limit}"
    games = conn.execute(q, (args.min_rating, args.min_rating)).fetchall()
    log.info(
        f"db={args.db} selected {len(games)} games "
        f"(rating>={args.min_rating}, variant=standard)")
    if not games:
        log.error("no games matched; aborting")
        return 2

    oracle = JassOracle(Path(args.jass), log)
    try:
        position_moves = _aggregate(games, oracle, args.max_plies, log)
    finally:
        oracle.close()

    n = _emit(position_moves, Path(args.out), args.min_count,
              args.min_rating, args.max_plies, log)
    if n == 0:
        log.error("no positions met --min-count; book would be empty")
        return 3
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
