// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Jean-François Collin
//
// Endgame bitbases generated by retrograde analysis.
//
// This translation unit owns the (lazily-built, thread-safe) tablebases
// for the small kings-only endgames currently supported and exposes a
// single probe entry point. New endgames are added as additional
// branches in `probe_kings_endgame`; the WIN/LOSS/DRAW labels are
// computed at first use.
//
// Caveat: the analysis produces theoretical values under ordinary
// chess-style win/loss/draw rules. The FMJD 16-move drawing rule that
// caps kings-only endgames is NOT modelled here, so for a few
// positions the bitbase will report a WIN that the real-world game
// would actually halve to a draw. This is a known limitation of the
// minimal v0.1 implementation and is signposted in the commit history.

#pragma once

#include "endgame.hpp"
#include "position.hpp"

namespace jass {

// Probe the kings-only endgame bitbases. Returns Unknown if the
// position falls outside the compiled-in tables.
EndgameResult probe_kings_endgame(const Position& pos);

}  // namespace jass
