// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Jean-François Collin
//
// Endgame bitbases generated by retrograde analysis.
//
// This translation unit owns the (lazily-built, thread-safe) tablebases
// for the small kings-only endgames currently supported and exposes a
// single probe entry point. New endgames are added as additional
// branches in `probe_kings_endgame`; the WIN/LOSS/DRAW labels are
// computed at first use.
//
// Caveat: the analysis produces theoretical values under ordinary
// chess-style win/loss/draw rules. The FMJD 16-move drawing rule that
// caps kings-only endgames is NOT modelled here, so for a few
// positions the bitbase will report a WIN that the real-world game
// would actually halve to a draw. This is a known limitation of the
// minimal v0.1 implementation and is signposted in the commit history.

#pragma once

#include "endgame.hpp"
#include "position.hpp"

namespace jass {

// Probe the kings-only endgame bitbases. Returns Unknown if the
// position falls outside the compiled-in tables.
EndgameResult probe_kings_endgame(const Position& pos);

// Build every kings-only bitbase now, so no later probe can pay for it.
//
// The tables are built by retrograde analysis on first probe, under a
// `std::call_once`. That probe happens inside `negamax`, so the build lands in
// the middle of a search — and a `call_once` cannot be interrupted by the
// deadline poll. Measured on the 3-kings-vs-3-kings position
// `W:WK46,K47,K48:BK3,K4,K5`: the 3-vs-1 table costs 5,15 s to build and the
// 2-vs-1 one 280 ms, so `go movetime 100` returned after 5,5 s — 55x its
// budget, at depth 3, having visited 2048 nodes.
//
// This is why the overshoot only ever showed up in king endgames, why raising
// the node-poll frequency from 0x3FF to 0xFF changed nothing, and why the A/B
// harness saw a milder "2-3.5x": there the cost is paid by whichever move first
// reaches such an endgame and is amortised over the rest of the game.
//
// Callers that run searches under a clock must call this before the clock
// starts. It is idempotent and thread-safe.
void warm_kings_endgame_bitbases();

}  // namespace jass
