#!/usr/bin/env bash
# id: 0030b-cycle9-10M-host-b
# description: Cycle 9 FULL — host B's quarter of a 10M run. Same shape
#              as the 0025a pilot (v5 NNUE labeller, halfmen encoding,
#              SIMD + incremental accumulator in the binary post-PR
#              #72/#73 merges), just scaled to 2.5M records per host
#              across 4 parallel hosts.
#
#              Tune the two big knobs BEFORE running:
#                * PER_SHARD / NSHARDS → total target records per host.
#                * EVAL_DEPTH         → set to 20 for production quality
#                                       (~30+ days wall on CPX62), or 16
#                                       for ~3-4× faster but noisier
#                                       labels. Decide after 0028's
#                                       pilot verdict.
#
#              REQUIRES JASS_HOST_FILTER=0030b- on host B's systemd env
#              so hosts B/C/D don't pick this job.
#
#              Pipeline:
#                0030b/b/c/d — four hosts each generate 2.5M records.
#                0031       — merge the four 2.5M shards into a 10M blob.
#                0032       — train Cycle 9 NNUE on the 10M.
#                0033       — bench Cycle 9 vs v5 → ELO verdict.
#
#              All four host scripts are mechanically identical except
#              for: their JASS_HOST_FILTER (0030b/b/c/d), their seed
#              base (5000/6000/7000/8000), and their output filename
#              (host-b/b/c/d.bin). Generated by mechanical sed from
#              this template.
#
# expected_duration: depth 20 + 16-vCPU CPX62 ≈ 9-10 days for 2.5M.
#                    depth 16 + 16-vCPU CPX62 ≈ 2-3 days for 2.5M.
set -uo pipefail
cd /root/jass

OUT_BASE="/root/jass/jobs/results/0030b-cycle9-10M-host-b"
ART="$OUT_BASE/artefacts.src"
mkdir -p "$ART"

# Sharding: one jass instance per vCPU. 16 shards × 156 250 records on
# a CPX62 (16 vCPU shared); the 4-vCPU CCX23 would want 4 × 625 000
# instead. Adjust to match the host.
NSHARDS=$(nproc)
TOTAL_RECORDS=2500000
PER_SHARD=$(( (TOTAL_RECORDS + NSHARDS - 1) / NSHARDS ))

# QUALITY KNOB — set to 20 for the full quality pass; 16 for a faster
# but noisier run. The Cycle-9 pilot (0025a at depth 16) is the signal
# for which is appropriate at this scale.
EVAL_DEPTH=20

PLAY_DEPTH=4
MAX_PLIES=200
# Seed range for host B: 5001..5000+NSHARDS, distinct from any prior
# corpus (0020a/b: 1001-2004, 0025a: 5001-5004 at the pilot — note
# overlap with this seed base but the 0025a pilot is the previous
# *short* run; we restart the 10M with a fresh slot 5001-5016 for
# 16-shard CPX62. If you re-run, bump SEED_BASE_OFFSET by NSHARDS to
# avoid corpus reuse.)
SEED_BASE=6000

NNUE_FILE=$(ls -t /root/jass/jobs/results/0018-train-with-master-bce/artefacts.src/nnue-*-q.bin 2>/dev/null | head -1)
if [ -z "$NNUE_FILE" ] || [ ! -f "$NNUE_FILE" ]; then
    echo "ABORT: v5 NNUE not found (0018-…/nnue-*-q.bin)"
    exit 3
fi

echo "=== host facts ==="
echo "host:        $(hostname)"
echo "filter:      ${JASS_HOST_FILTER:-(unset, expected '0030b-')}"
echo "nproc:       $(nproc)"
echo "mem:         $(free -h | awk '/^Mem:/ {print $2}')"
echo "disk:        $(df -h /root | awk 'NR==2 {print $4" free of "$2}')"
echo "shards:      $NSHARDS × $PER_SHARD = $((NSHARDS * PER_SHARD)) records target"
echo "eval depth:  $EVAL_DEPTH"
echo "NNUE:        $NNUE_FILE"
ls -lh "$NNUE_FILE"

if [ "$NSHARDS" -lt 4 ]; then
    echo "ABORT: host has only $NSHARDS vCPU; expected a CCX23 (4) or larger"
    exit 3
fi

echo
echo "=== rebuilding jass ==="
cmake --build build -j"$NSHARDS" 2>&1 | tail -5
echo "jass: $(./build/jass --version)"

echo
echo "=== launching $NSHARDS parallel shards (NNUE=v5, depth=$EVAL_DEPTH) ==="
START=$(date +%s)
pids=()
for shard in $(seq 1 $NSHARDS); do
    seed=$((SEED_BASE + shard))
    (
        START_SH=$(date +%s)
        ./build/jass --gen-data-wdl \
            "$PER_SHARD" \
            "$ART/shard-$shard.bin" \
            "$EVAL_DEPTH" "$PLAY_DEPTH" "$MAX_PLIES" "$seed" \
            --nnue "$NNUE_FILE" \
            > "$ART/shard-$shard.log" 2>&1
        rc=$?
        END_SH=$(date +%s)
        echo "$rc $((END_SH - START_SH))" > "$ART/shard-$shard.result"
        exit $rc
    ) &
    pids+=($!)
    echo "  shard $shard launched as pid $! (seed $seed)"
done

echo
echo "=== waiting on all shards ==="
fail=0
for i in "${!pids[@]}"; do
    p="${pids[$i]}"
    if wait "$p"; then
        echo "  pid $p: OK"
    else
        rc=$?
        echo "  pid $p: FAILED rc=$rc"
        fail=$((fail + 1))
    fi
done
END=$(date +%s)
WALL=$((END - START))

if [ "$fail" -gt 0 ]; then
    echo "ABORT: $fail / $NSHARDS shards failed"
    exit 4
fi

# Canari WDL (propagation 2026-07-28). Ces templates pré-L3 ne passent pas par
# `selfplay_frontier.py merge`, où la garde est câblée pour la chaîne L3. On la
# rappelle donc ici, sur les shards produits. Elle refuse un corpus vidé de ses
# nulles — le symptôme du défaut de racine nulle d'avant 9c1d1e8e (4,8 % de
# nulles au lieu de 20,3 %), et de toute cause future qui ferait la même chose.
for _shard_data in "$ART"/shard-*.bin; do
    [ -e "$_shard_data" ] || continue
    python3 jobs/tools/assert_corpus_wdl.py --data "$_shard_data" ||
        { echo "ABORT: corpus WDL aberrant dans $_shard_data"; exit 6; }
done

echo
echo "=== merging this host's $NSHARDS shards into host-b.bin ==="
python3 - <<PY
import struct
from pathlib import Path

MAGIC = b"JNNW"
HEADER_SZ = 8
RECORD_SZ = 38

art = Path("$ART")
shards = sorted(art.glob("shard-*.bin"))
print(f"  inputs: {[s.name for s in shards]}")

total = 0
with (art / "host-b.bin").open("wb") as out:
    out.write(MAGIC)
    out.write(struct.pack("<I", 0))
    for s in shards:
        raw = s.read_bytes()
        assert raw[:4] == MAGIC, f"{s}: bad magic"
        cnt = struct.unpack_from("<I", raw, 4)[0]
        expected = HEADER_SZ + cnt * RECORD_SZ
        assert len(raw) == expected, f"{s}: bad size"
        out.write(raw[HEADER_SZ:])
        total += cnt
    out.seek(4)
    out.write(struct.pack("<I", total))
print(f"  merged {total} records into {art}/host-b.bin")
PY

echo
echo "=========================================================="
echo "       0030b CYCLE-9 10M (host B) SUMMARY"
echo "=========================================================="
echo "  host:           $(hostname)"
echo "  filter env:     ${JASS_HOST_FILTER:-UNSET}"
echo "  NNUE labeller:  $(basename "$NNUE_FILE")  (v5, Cycle 8 BCE)"
echo "  eval depth:     $EVAL_DEPTH"
echo "  shards:         $NSHARDS × $PER_SHARD = $((NSHARDS * PER_SHARD)) records target"
echo "  wall:           ${WALL}s ($(python3 -c "print(round($WALL/3600,1))") h, $(python3 -c "print(round($WALL/86400,1))") d)"
echo "  per-shard rcs:"
for f in "$ART"/shard-*.result; do
    [ -f "$f" ] && echo "    $(basename $f): $(cat $f)"
done
echo "  output:         host-b.bin ($(ls -lh "$ART/host-b.bin" | awk '{print $5}'))"
echo "=========================================================="
echo
echo "Next: wait for 0030b/c/d to finish on their hosts, scp their"
echo "host-*.bin to a merge host, then queue 0031-merge-cycle9-10M"
echo "to combine the four 2.5M halves into a single 10M training blob."
