#!/usr/bin/env python3
"""Render and validate the prospective B2 full-teacher implementation.

The renderer is deliberately a narrow adapter around the audited historical
``src/deep_sibling_teacher.cpp``.  It changes Engine lifetime and adds receipts;
it does not change budgets, columns, sibling ordering, scores, or exact/TB
handling.  Source drift and receipt drift fail closed.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence


BASE_SOURCE_NORMALIZED_SHA256 = (
    "50813baaae1934ad155d05b6d28c8a908925b06d510863976c7cee9d6e98deb4"
)
ADAPTER_SCHEMA = "jass.adaptive_sibling_b2_teacher_source_adapter.v1"
SHARD_SCHEMA = "jass.deep_sibling_teacher_extract.v1"
MERGED_SCHEMA = "jass.adaptive_sibling_b2_teacher_aggregate.v1"
SELECTION_SCHEMA = "jass.adaptive_sibling_b2_target_blind_selection.v1"
INPUT_AUTH_SCHEMA = "jass.adaptive_sibling_b2_teacher_input_auth.v1"
BUDGETS = (5_000, 50_000, 200_000)
REQUIRED_EGDB_CACHE_MB = 256
SELECTED_PARENTS = 4_000
JNNW_RECORD_SIZE = 38
SHARD_COUNT = 16
UINT64_MAX = (1 << 64) - 1

PREFIX = '''// Generated by jobs/tools/adaptive_sibling_b2_teacher_source.py. Do not edit.
#ifndef JASS_EGDB
#error "B2 full teacher requires a build configured with JASS_EGDB=ON"
#endif
#include "pattern_jass_bridge.hpp"
#include "scan_eval.hpp"
#if defined(_WIN32)
extern "C" char** _environ;
#define JASS_B2_ENVIRON _environ
#else
extern "C" char** environ;
#define JASS_B2_ENVIRON environ
#endif
#define load_pattern_jass_network load_eval_network
'''

SUFFIX = '''
#undef load_pattern_jass_network
#undef JASS_B2_ENVIRON
'''

ENGINE_DECL = "    Engine engine(tt_mb);\n    engine.use_book(false);\n"
COUNTERS_OLD = "    std::uint64_t emitted_siblings{0};\n    std::uint64_t rule_terminal_children{0};"
COUNTERS_NEW = (
    "    std::uint64_t emitted_siblings{0};\n"
    "    std::uint64_t engine_constructions{0};\n"
    "    std::uint64_t rule_terminal_children{0};"
)
SEARCH_SIG_OLD = """SearchObs run_fresh_search(Engine& engine,
                           const Position& child,"""
SEARCH_SIG_NEW = """SearchObs run_fresh_search(std::size_t tt_mb,
                           std::uint64_t& engine_constructions,
                           const Position& child,"""
SEARCH_BODY_OLD = """    engine.clear_tt();
    engine.set_position(child);"""
SEARCH_BODY_NEW = """    Engine engine(tt_mb);
    ++engine_constructions;
    engine.use_book(false);
    engine.clear_tt();
    engine.set_position(child);"""
CALL_OLD = "run_fresh_search(engine, child,"
CALL_NEW = "run_fresh_search(tt_mb, c.engine_constructions, child,"

ENV_HELPER_ANCHOR = """constexpr std::size_t DEFAULT_TT_MB = 16;

struct DiskRow {"""
ENV_HELPER_REPLACEMENT = """constexpr std::size_t DEFAULT_TT_MB = 16;

const char* first_jass_environment_entry() noexcept {
    for (char** item = JASS_B2_ENVIRON; item != nullptr && *item != nullptr; ++item) {
        if (std::strncmp(*item, "JASS_", 5) == 0) return *item;
    }
    return nullptr;
}

struct DiskRow {"""

USAGE_OLD = """    if (argc < 7 || argc > 11) {
        std::cerr << "usage: jass_deep_sibling_teacher <parents.jnnw> <children.jnnw> "
                     "<groups.tsv> <report.json> <curriculum.pjtw> <egdb_dir> "
                     "[shard=0] [nshards=1] [tt_mb=16] [egdb_cache_mb=2048]\\n";
        return 2;
    }
    if (std::getenv("JASS_TB_MOVE_ORDER_POLICY") != nullptr) {
        std::cerr << "error: JASS_TB_MOVE_ORDER_POLICY must be absent for the frozen teacher\\n";
        return 2;
    }
"""
USAGE_NEW = """    if (argc != 11) {
        std::cerr << "usage: jass_deep_sibling_teacher <parents.jnnw> <children.jnnw> "
                     "<groups.tsv> <report.json> <curriculum.pjtw> <egdb_dir> "
                     "<shard> <nshards> <tt_mb> <egdb_cache_mb=256>\\n";
        return 2;
    }
    if (const char* inherited = first_jass_environment_entry(); inherited != nullptr) {
        const char* equals = std::strchr(inherited, '=');
        std::cerr << "error: JASS_* environment must be absent for B2 teacher: "
                  << std::string(inherited, equals == nullptr ? std::strlen(inherited)
                                                              : equals - inherited)
                  << '\\n';
        return 2;
    }
"""

ARGS_OLD = """    const int shard = argc >= 8 ? std::stoi(argv[7]) : 0;
    const int nshards = argc >= 9 ? std::stoi(argv[8]) : 1;
    const std::size_t tt_mb = argc >= 10
        ? static_cast<std::size_t>(std::max(1, std::stoi(argv[9]))) : DEFAULT_TT_MB;
    const int egdb_cache_mb = argc >= 11 ? std::max(64, std::stoi(argv[10])) : 2048;
    if (nshards <= 0 || shard < 0 || shard >= nshards) {
        std::cerr << "error: invalid shard/nshards\\n";
        return 2;
    }
"""
ARGS_NEW = """    const int shard = std::stoi(argv[7]);
    const int nshards = std::stoi(argv[8]);
    const int tt_mb_arg = std::stoi(argv[9]);
    const int egdb_cache_mb = std::stoi(argv[10]);
    if (nshards <= 0 || shard < 0 || shard >= nshards || tt_mb_arg <= 0) {
        std::cerr << "error: invalid shard/nshards/tt_mb\\n";
        return 2;
    }
    if (egdb_dir.empty() || egdb_cache_mb != 256) {
        std::cerr << "error: B2 teacher requires explicit EGDB directory and cache 256 MiB\\n";
        return 2;
    }
    const std::size_t tt_mb = static_cast<std::size_t>(tt_mb_arg);
"""

INVALID_OLD = "        if (!valid_row(row)) { ++c.invalid_rows; continue; }"
INVALID_NEW = """        if (!valid_row(row)) {
            ++c.invalid_rows;
            std::cerr << "error: invalid selected-parent row " << idx << '\\n';
            return 4;
        }"""

SEARCHES_OLD = """            const SearchObs s5 = run_fresh_search(engine, child, curriculum.get(), CHEAP_BUDGET, tb_cap);
            const SearchObs s50 = run_fresh_search(engine, child, curriculum.get(), SCREEN_BUDGET, tb_cap);
            const SearchObs s200 = run_fresh_search(engine, child, curriculum.get(), TEACHER_BUDGET, tb_cap);
            ++c.cheap_searches; ++c.screen_searches; ++c.teacher_searches;"""
SEARCHES_NEW = """            const SearchObs s5 = run_fresh_search(tt_mb, c.engine_constructions, child, curriculum.get(), CHEAP_BUDGET, tb_cap);
            ++c.cheap_searches;
            const SearchObs s50 = run_fresh_search(tt_mb, c.engine_constructions, child, curriculum.get(), SCREEN_BUDGET, tb_cap);
            ++c.screen_searches;
            const SearchObs s200 = run_fresh_search(tt_mb, c.engine_constructions, child, curriculum.get(), TEACHER_BUDGET, tb_cap);
            ++c.teacher_searches;"""

TB_CAP_OLD = """    if (tb_cap <= 0) {
        std::cerr << "error: invalid EGDB max pieces\\n";
        return 3;
    }"""
TB_CAP_NEW = """    if (tb_cap <= 0 || tb_cap > 40) {
        std::cerr << "error: invalid EGDB max pieces\\n";
        return 3;
    }"""

REPORT_SIG_OLD = """                  int tb_cap,
                  std::size_t tt_mb,
                  const Counters& c) {
    std::ofstream out(path);"""
REPORT_SIG_NEW = """                  int tb_cap,
                  std::size_t tt_mb,
                  int egdb_cache_mb,
                  const Counters& c) {
    if (c.cheap_searches != c.emitted_siblings
        || c.screen_searches != c.emitted_siblings
        || c.teacher_searches != c.emitted_siblings
        || c.engine_constructions != c.cheap_searches + c.screen_searches + c.teacher_searches) {
        throw std::runtime_error("B2 teacher counter contract mismatch");
    }
    std::ofstream out(path);"""

REPORT_FIELDS_OLD = """        << "  \\"fresh_tt_each_search\\": true,\\n"
        << "  \\"node_limit_mode\\": \\"exact\\",\\n"""
REPORT_FIELDS_NEW = """        << "  \\"fresh_tt_each_search\\": true,\\n"
        << "  \\"fresh_engine_each_search\\": true,\\n"
        << "  \\"engine_constructions\\": " << c.engine_constructions << ",\\n"
        << "  \\"jass_prefixed_environment_count\\": 0,\\n"
        << "  \\"egdb_configuration_source\\": \\"explicit_positional_arguments\\",\\n"
        << "  \\"egdb_required_available\\": true,\\n"
        << "  \\"egdb_cache_mb\\": " << egdb_cache_mb << ",\\n"
        << "  \\"node_limit_mode\\": \\"exact\\",\\n"""

REPORT_CALL_OLD = "write_report(report_path, declared, shard, nshards, tb_cap, tt_mb, c);"
REPORT_CALL_NEW = (
    "write_report(report_path, declared, shard, nshards, tb_cap, tt_mb, "
    "egdb_cache_mb, c);"
)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _normalize_source(raw: bytes) -> bytes:
    normalized = raw.replace(b"\r\n", b"\n")
    if b"\r" in normalized:
        raise ValueError("base source contains unsupported bare CR bytes")
    try:
        normalized.decode("utf-8")
    except UnicodeDecodeError as exc:
        raise ValueError("base source is not UTF-8") from exc
    return normalized


def replace_exact(text: str, old: str, new: str, count: int = 1) -> str:
    actual = text.count(old)
    if actual != count:
        raise ValueError(f"expected {count} occurrences of {old!r}, got {actual}")
    return text.replace(old, new)


def render(source: str) -> str:
    normalized = source.replace("\r\n", "\n")
    if "\r" in normalized:
        raise ValueError("base source contains unsupported bare CR")
    digest = _sha256(normalized.encode("utf-8"))
    if digest != BASE_SOURCE_NORMALIZED_SHA256:
        raise ValueError(
            "unexpected normalized base source SHA256: "
            f"expected {BASE_SOURCE_NORMALIZED_SHA256}, got {digest}"
        )

    out = normalized
    for old, new in (
        (COUNTERS_OLD, COUNTERS_NEW),
        (ENV_HELPER_ANCHOR, ENV_HELPER_REPLACEMENT),
        (SEARCH_SIG_OLD, SEARCH_SIG_NEW),
        (SEARCH_BODY_OLD, SEARCH_BODY_NEW),
        (REPORT_SIG_OLD, REPORT_SIG_NEW),
        (REPORT_FIELDS_OLD, REPORT_FIELDS_NEW),
        (USAGE_OLD, USAGE_NEW),
        (ARGS_OLD, ARGS_NEW),
        (INVALID_OLD, INVALID_NEW),
        (SEARCHES_OLD, SEARCHES_NEW),
        (TB_CAP_OLD, TB_CAP_NEW),
        (REPORT_CALL_OLD, REPORT_CALL_NEW),
    ):
        out = replace_exact(out, old, new)

    # Remove the sole long-lived Engine after inserting the local constructor.
    out = replace_exact(out, ENGINE_DECL, "")

    if out.count("Engine engine(tt_mb);") != 1:
        raise ValueError("rendered source must contain exactly one local Engine constructor")
    if out.count(CALL_OLD) != 0 or out.count(CALL_NEW) != 3:
        raise ValueError("rendered source does not contain exactly three fresh searches")
    for token in (
        "constexpr std::uint64_t CHEAP_BUDGET = 5'000;",
        "constexpr std::uint64_t SCREEN_BUDGET = 50'000;",
        "constexpr std::uint64_t TEACHER_BUDGET = 200'000;",
        "NodeLimitMode::Exact",
        "q5k_parent",
        "q50_parent",
        "q200_parent",
    ):
        if token not in out:
            raise ValueError(f"rendered source lost frozen teacher token {token!r}")
    return PREFIX + out + SUFFIX


def render_file(source_path: Path, output_path: Path, receipt_path: Path) -> dict[str, Any]:
    raw = source_path.read_bytes()
    normalized = _normalize_source(raw)
    rendered = render(normalized.decode("utf-8")).encode("utf-8")
    receipt = {
        "schema": ADAPTER_SCHEMA,
        "base_source_path": source_path.as_posix(),
        "base_source_sha256": _sha256(raw),
        "base_source_normalized_sha256": _sha256(normalized),
        "rendered_source_path": output_path.as_posix(),
        "rendered_source_sha256": _sha256(rendered),
        "rendered_source_bytes": len(rendered),
        "budgets_nodes": list(BUDGETS),
        "fresh_engine_each_search": True,
        "engine_constructions_per_sibling": 3,
        "book_enabled": False,
        "threads_per_search": 1,
        "node_limit_mode": "exact",
        "egdb_build_required": True,
        "egdb_configuration_source": "explicit_positional_arguments",
        "egdb_cache_mb": REQUIRED_EGDB_CACHE_MB,
        "jass_prefixed_environment": [],
        "engine_lifecycle_changed": True,
        "frozen_budgets_columns_and_score_semantics_changed": False,
    }
    _require_distinct_paths((source_path, output_path, receipt_path))
    _publish_files(
        {output_path: rendered, receipt_path: _json_bytes(receipt)},
        protected_inputs=(source_path,),
    )
    return receipt


def _validate_sha256(value: Any, label: str) -> str:
    if not isinstance(value, str) or len(value) != 64 \
            or any(char not in "0123456789abcdef" for char in value):
        raise ValueError(f"{label} must be lowercase SHA256 hex")
    return value


def verify_selection_input(
    parents_path: Path,
    selection_report_path: Path,
    expected_selection_report_sha256: str,
) -> dict[str, Any]:
    """Authenticate the sealed target-blind JNNW before any teacher search."""
    expected_report_sha = _validate_sha256(
        expected_selection_report_sha256, "expected selection report SHA256"
    )
    report_raw = selection_report_path.read_bytes()
    report_sha = _sha256(report_raw)
    if report_sha != expected_report_sha:
        raise ValueError("selection report SHA256 differs from authenticated receipt")
    try:
        report = json.loads(report_raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("selection report is not valid UTF-8 JSON") from exc
    if not isinstance(report, dict) or report.get("schema") != SELECTION_SCHEMA:
        raise ValueError("unexpected selection report schema")
    outputs = report.get("outputs")
    if not isinstance(outputs, dict) or not isinstance(outputs.get("parents_jnnw"), dict):
        raise ValueError("selection report lacks outputs.parents_jnnw")
    sealed = outputs["parents_jnnw"]
    required = frozenset(("sha256", "size_bytes", "records"))
    if frozenset(sealed) != required:
        raise ValueError("selection report parents_jnnw seal keys differ")
    sealed_sha = _validate_sha256(sealed["sha256"], "parents_jnnw.sha256")
    if not _is_int(sealed["size_bytes"]) or not _is_int(sealed["records"]):
        raise ValueError("parents_jnnw size and records must be integers")
    if sealed["records"] != SELECTED_PARENTS:
        raise ValueError("selection report must seal exactly 4000 parents")

    raw = parents_path.read_bytes()
    if _sha256(raw) != sealed_sha or len(raw) != sealed["size_bytes"]:
        raise ValueError("parents.jnnw bytes differ from selection report seal")
    expected_size = 8 + JNNW_RECORD_SIZE * SELECTED_PARENTS
    if len(raw) != expected_size or raw[:4] != b"JNNW" \
            or int.from_bytes(raw[4:8], "little") != SELECTED_PARENTS:
        raise ValueError("parents.jnnw header/count/size is not the B2 contract")
    for row_index in range(SELECTED_PARENTS):
        target = 8 + JNNW_RECORD_SIZE * row_index + 33
        if raw[target:target + 5] != b"\0" * 5:
            raise ValueError(f"parents.jnnw target bytes are nonzero at row {row_index}")
    return {
        "schema": INPUT_AUTH_SCHEMA,
        "selection_report_sha256": report_sha,
        "selection_report_schema": SELECTION_SCHEMA,
        "parents_jnnw_sha256": sealed_sha,
        "parents_jnnw_size_bytes": len(raw),
        "parents_jnnw_records": SELECTED_PARENTS,
        "target_bytes_checked": 5 * SELECTED_PARENTS,
        "target_bytes_nonzero": 0,
        "teacher_scores_read": 0,
        "authenticated_before_teacher": True,
    }


def _is_int(value: Any) -> bool:
    return isinstance(value, int) and not isinstance(value, bool)


def _require_int(
    report: Mapping[str, Any], key: str, minimum: int = 0, maximum: int = UINT64_MAX
) -> int:
    value = report.get(key)
    if not _is_int(value) or not minimum <= value <= maximum:
        raise ValueError(f"{key} must be an integer in [{minimum},{maximum}]")
    return value


SHARD_REPORT_KEYS = frozenset(
    {
        "schema", "input_parents", "shard", "nshards", "book_enabled",
        "threads_per_search", "fresh_tt_each_search", "fresh_engine_each_search",
        "engine_constructions", "jass_prefixed_environment_count",
        "egdb_configuration_source", "egdb_required_available", "egdb_cache_mb",
        "node_limit_mode", "cheap_budget_nodes", "screen_budget_nodes",
        "teacher_budget_nodes", "tt_mb", "egdb_max_pieces", "source_rows",
        "processed_parent_rows", "invalid_rows", "duplicate_move_entries",
        "emitted_siblings", "rule_terminal_children", "exact_tb_children",
        "cheap_searches", "screen_searches", "teacher_searches", "cheap_nodes",
        "screen_nodes", "teacher_nodes", "teacher_scores_produced",
        "stable_pairs_selected", "fits", "strength_games", "promotion_authorized",
    }
)

SUM_FIELDS = (
    "processed_parent_rows", "invalid_rows", "duplicate_move_entries",
    "emitted_siblings", "engine_constructions", "rule_terminal_children",
    "exact_tb_children", "cheap_searches", "screen_searches", "teacher_searches",
    "cheap_nodes", "screen_nodes", "teacher_nodes",
)

def validate_shard_report(report: Mapping[str, Any]) -> None:
    keys = frozenset(report)
    if keys != SHARD_REPORT_KEYS:
        raise ValueError(
            f"shard report keys differ: missing={sorted(SHARD_REPORT_KEYS - keys)}, "
            f"extra={sorted(keys - SHARD_REPORT_KEYS)}"
        )
    expected = {
        "schema": SHARD_SCHEMA,
        "book_enabled": False,
        "threads_per_search": 1,
        "fresh_tt_each_search": True,
        "fresh_engine_each_search": True,
        "jass_prefixed_environment_count": 0,
        "egdb_configuration_source": "explicit_positional_arguments",
        "egdb_required_available": True,
        "egdb_cache_mb": REQUIRED_EGDB_CACHE_MB,
        "node_limit_mode": "exact",
        "cheap_budget_nodes": BUDGETS[0],
        "screen_budget_nodes": BUDGETS[1],
        "teacher_budget_nodes": BUDGETS[2],
        "teacher_scores_produced": True,
        "stable_pairs_selected": False,
        "fits": 0,
        "strength_games": 0,
        "promotion_authorized": False,
    }
    for key, value in expected.items():
        if report.get(key) != value or type(report.get(key)) is not type(value):
            raise ValueError(f"unexpected {key}: {report.get(key)!r}")

    input_parents = _require_int(report, "input_parents", SELECTED_PARENTS, SELECTED_PARENTS)
    shard = _require_int(report, "shard", 0, SHARD_COUNT - 1)
    nshards = _require_int(report, "nshards", SHARD_COUNT, SHARD_COUNT)
    _require_int(report, "tt_mb", 1)
    _require_int(report, "egdb_max_pieces", 1, 40)
    if shard >= nshards:
        raise ValueError("shard must be smaller than nshards")
    if _require_int(report, "source_rows") != input_parents:
        raise ValueError("source_rows must equal input_parents")
    expected_processed = len(range(shard, input_parents, nshards))
    if _require_int(report, "processed_parent_rows") != expected_processed:
        raise ValueError("processed_parent_rows disagrees with modulo sharding")
    if _require_int(report, "invalid_rows") != 0:
        raise ValueError("invalid selected-parent rows are forbidden")
    for key in SUM_FIELDS:
        _require_int(report, key)

    emitted = report["emitted_siblings"]
    processed = report["processed_parent_rows"]
    if not 2 * processed <= emitted <= 16 * processed:
        raise ValueError("emitted_siblings outside frozen 2..16 per-parent support")
    if report["rule_terminal_children"] + report["exact_tb_children"] > emitted:
        raise ValueError("exact child counters exceed emitted siblings")
    for key in ("cheap_searches", "screen_searches", "teacher_searches"):
        if report[key] != emitted:
            raise ValueError(f"{key} must equal emitted_siblings")
    if report["engine_constructions"] != 3 * emitted:
        raise ValueError("engine_constructions must equal 3*emitted_siblings")
    for key, budget in (("cheap_nodes", BUDGETS[0]), ("screen_nodes", BUDGETS[1]),
                        ("teacher_nodes", BUDGETS[2])):
        if report[key] > emitted * budget:
            raise ValueError(f"{key} exceeds its exact-node cap")


def merge_reports(reports: Sequence[Mapping[str, Any]]) -> dict[str, Any]:
    if len(reports) != SHARD_COUNT:
        raise ValueError(f"exactly {SHARD_COUNT} shard reports are required")
    checked = [dict(report) for report in reports]
    for report in checked:
        validate_shard_report(report)
    nshards = checked[0]["nshards"]
    if len(checked) != nshards:
        raise ValueError("report count must equal nshards")
    by_shard = {report["shard"]: report for report in checked}
    if len(by_shard) != nshards or set(by_shard) != set(range(nshards)):
        raise ValueError("shards must be unique and exhaustive 0..nshards-1")
    ordered = [by_shard[i] for i in range(nshards)]
    invariant_keys = (
        "input_parents", "nshards", "book_enabled", "threads_per_search",
        "fresh_tt_each_search", "fresh_engine_each_search",
        "jass_prefixed_environment_count", "egdb_configuration_source",
        "egdb_required_available", "egdb_cache_mb", "node_limit_mode",
        "cheap_budget_nodes", "screen_budget_nodes", "teacher_budget_nodes",
        "tt_mb", "egdb_max_pieces", "teacher_scores_produced",
        "stable_pairs_selected", "fits", "strength_games", "promotion_authorized",
    )
    for key in invariant_keys:
        if any(report[key] != ordered[0][key] for report in ordered[1:]):
            raise ValueError(f"shard invariant differs for {key}")

    aggregate: dict[str, Any] = {
        "schema": MERGED_SCHEMA,
        "nshards": nshards,
        "input_parents": ordered[0]["input_parents"],
        "book_enabled": False,
        "threads_per_search": 1,
        "fresh_tt_each_search": True,
        "fresh_engine_each_search": True,
        "jass_prefixed_environment_count": 0,
        "egdb_configuration_source": "explicit_positional_arguments",
        "egdb_required_available": True,
        "egdb_cache_mb": REQUIRED_EGDB_CACHE_MB,
        "node_limit_mode": "exact",
        "budgets_nodes": list(BUDGETS),
        "tt_mb": ordered[0]["tt_mb"],
        "egdb_max_pieces": ordered[0]["egdb_max_pieces"],
        "teacher_scores_produced": True,
        "stable_pairs_selected": False,
        "fits": 0,
        "strength_games": 0,
        "promotion_authorized": False,
        "shards": ordered,
    }
    for key in SUM_FIELDS:
        value = sum(report[key] for report in ordered)
        if value > UINT64_MAX:
            raise ValueError(f"merged {key} exceeds uint64")
        aggregate[key] = value
    emitted = aggregate["emitted_siblings"]
    if aggregate["processed_parent_rows"] != aggregate["input_parents"]:
        raise ValueError("merged processed parents must equal input parents")
    if aggregate["cheap_searches"] != emitted or aggregate["screen_searches"] != emitted \
            or aggregate["teacher_searches"] != emitted:
        raise ValueError("merged per-budget searches must equal emitted siblings")
    if aggregate["engine_constructions"] != 3 * emitted:
        raise ValueError("merged engine constructions must equal 3*emitted siblings")
    return aggregate


def load_and_merge_reports(paths: Iterable[Path]) -> dict[str, Any]:
    reports: list[Mapping[str, Any]] = []
    for path in paths:
        value = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(value, dict):
            raise ValueError(f"report is not a JSON object: {path}")
        reports.append(value)
    return merge_reports(reports)


def _path_key(path: Path) -> str:
    return os.path.normcase(os.path.normpath(str(path.resolve(strict=False)))).casefold()


def _require_distinct_paths(paths: Sequence[Path]) -> None:
    keys = [_path_key(path) for path in paths]
    if len(set(keys)) != len(keys):
        raise ValueError("input/output paths must be pairwise distinct")


def _json_bytes(value: Mapping[str, Any]) -> bytes:
    return (json.dumps(value, sort_keys=True, ensure_ascii=True, indent=2) + "\n").encode("ascii")


def _publish_files(
    values: Mapping[Path, bytes], *, protected_inputs: Sequence[Path] = ()
) -> None:
    outputs = list(values)
    temporaries = [Path(str(path) + ".tmp") for path in outputs]
    all_paths = [*protected_inputs, *outputs, *temporaries]
    keys = [_path_key(path) for path in all_paths]
    if len(set(keys)) != len(keys):
        raise ValueError("input/output/temporary paths must be pairwise distinct")
    if any(path.exists() for path in [*outputs, *temporaries]):
        raise ValueError("refusing existing output or temporary path")
    published: list[Path] = []
    try:
        for path, temporary in zip(outputs, temporaries):
            path.parent.mkdir(parents=True, exist_ok=True)
            temporary.write_bytes(values[path])
            if temporary.read_bytes() != values[path]:
                raise ValueError(f"temporary output verification failed: {path}")
        for path, temporary in zip(outputs, temporaries):
            os.replace(temporary, path)
            published.append(path)
        for path in outputs:
            if path.read_bytes() != values[path]:
                raise ValueError(f"published output verification failed: {path}")
    except Exception:
        for path in [*temporaries, *published]:
            path.unlink(missing_ok=True)
        raise


def _write_json(
    path: Path, value: Mapping[str, Any], *, protected_inputs: Sequence[Path] = ()
) -> None:
    _publish_files({path: _json_bytes(value)}, protected_inputs=protected_inputs)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    sub = parser.add_subparsers(dest="command", required=True)
    render_cmd = sub.add_parser("render", help="render the pinned B2 teacher source")
    render_cmd.add_argument("--source", type=Path, default=Path("src/deep_sibling_teacher.cpp"))
    render_cmd.add_argument("--output", type=Path, required=True)
    render_cmd.add_argument("--receipt", type=Path, required=True)
    merge_cmd = sub.add_parser("merge-reports", help="strictly validate and merge shard receipts")
    merge_cmd.add_argument("--report", type=Path, action="append", required=True)
    merge_cmd.add_argument("--output", type=Path, required=True)
    verify_cmd = sub.add_parser(
        "verify-selection", help="authenticate sealed selected parents before teacher search"
    )
    verify_cmd.add_argument("--parents-jnnw", type=Path, required=True)
    verify_cmd.add_argument("--selection-report", type=Path, required=True)
    verify_cmd.add_argument("--expected-selection-report-sha256", required=True)
    verify_cmd.add_argument("--receipt", type=Path, required=True)
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    if args.command == "render":
        render_file(args.source, args.output, args.receipt)
    elif args.command == "merge-reports":
        _write_json(
            args.output,
            load_and_merge_reports(args.report),
            protected_inputs=args.report,
        )
    else:
        receipt = verify_selection_input(
            args.parents_jnnw,
            args.selection_report,
            args.expected_selection_report_sha256,
        )
        _write_json(
            args.receipt,
            receipt,
            protected_inputs=(args.parents_jnnw, args.selection_report),
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
