#!/usr/bin/env python3
"""Mine causal WIN->DRAW/LOSS events and build matched teacher corpora.

Two source modes are supported:

* ``--trajectories`` consumes the replayable JSONL sidecar emitted by current
  self-play and runs one symmetric oracle over its unique positions.
* ``--gen`` + ``--oracle`` reconstructs historical sample-every=1 games.  An
  adjacency is accepted only when ``jass --dump-children`` proves that the
  next record is an actual legal child; all other adjacencies are boundaries.

For every quiet causal event, every unplayed sibling is evaluated with the
same oracle.  Parents with at least one WIN sibling produce:

* B1 ordinary oracle-labelled sibling records;
* B2 one explicit immediate-child pair (good > played bad);
* aligned parent/good/bad move files from which B3 leaf pairs are generated by
  ``jass --gen-siblings --played-moves ... --dominated-moves ... --leaf-mode``.

The train/holdout split is by source game.  B2 and B3 therefore share exactly
the same parents, pairs and split, as required by codex_review_v3_2.
"""
from __future__ import annotations

import argparse
import gzip
import hashlib
import json
import re
import struct
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

REC = 38
MOVE_RE = re.compile(r"^(\d+)[x-](\d+)$")


def _squares(bb: int) -> list[int]:
    return [index + 1 for index in range(50) if (bb >> index) & 1]


def record_to_fen(record: bytes) -> str:
    wm, wk, bm, bk = struct.unpack_from("<4Q", record, 0)
    side = "W" if record[32] == 0 else "B"
    white = [str(sq) for sq in _squares(wm)] + [f"K{sq}" for sq in _squares(wk)]
    black = [str(sq) for sq in _squares(bm)] + [f"K{sq}" for sq in _squares(bk)]
    return f"{side}:W{','.join(white)}:B{','.join(black)}"


def _expand(entries: str) -> tuple[int, int]:
    men = kings = 0
    for token in entries.split(","):
        token = token.strip()
        if not token:
            continue
        king = token[:1].upper() == "K"
        if king:
            token = token[1:]
        if "-" in token:
            first, last = map(int, token.split("-", 1))
            squares = range(first, last + 1)
        else:
            squares = (int(token),)
        for square in squares:
            if not 1 <= square <= 50:
                raise ValueError(f"invalid square {square}")
            if king:
                kings |= 1 << (square - 1)
            else:
                men |= 1 << (square - 1)
    return men, kings


def fen_to_record(fen: str, wdl_stm: int = 0) -> bytes:
    parts = fen.strip().split(":")
    if len(parts) != 3 or parts[0] not in {"W", "B"}:
        raise ValueError(f"bad FEN: {fen!r}")
    colors: dict[str, tuple[int, int]] = {}
    for part in parts[1:]:
        if not part or part[0] not in {"W", "B"}:
            raise ValueError(f"bad FEN color list: {fen!r}")
        colors[part[0]] = _expand(part[1:])
    wm, wk = colors.get("W", (0, 0))
    bm, bk = colors.get("B", (0, 0))
    return (
        struct.pack("<4Q", wm, wk, bm, bk)
        + bytes([0 if parts[0] == "W" else 1])
        + struct.pack("<i", 0)
        + struct.pack("<b", int(wdl_stm))
    )


def board_key(fen: str) -> bytes:
    return fen_to_record(fen)[:33]


def signed_wdl(record: bytes) -> int:
    return struct.unpack_from("<b", record, 37)[0]


def read_jnnw(path: Path) -> list[bytes]:
    raw = path.read_bytes()
    if len(raw) < 8 or raw[:4] != b"JNNW":
        raise ValueError(f"not JNNW: {path}")
    count = struct.unpack_from("<I", raw, 4)[0]
    if len(raw) != 8 + count * REC:
        raise ValueError(f"JNNW size/count mismatch: {path}")
    return [raw[8 + i * REC:8 + (i + 1) * REC] for i in range(count)]


def write_jnnw(path: Path, records: list[bytes]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(b"JNNW" + struct.pack("<I", len(records)) + b"".join(records))


def run_checked(command: list[str], *, timeout: int | None = None) -> None:
    proc = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=timeout)
    if proc.returncode != 0:
        tail = proc.stderr[-2000:].decode("utf-8", "replace")
        raise RuntimeError(f"command failed ({proc.returncode}): {command[0]} ...\n{tail}")


def dump_children(jass: str, fens: list[str], work: Path, stem: str) -> list[list[dict]]:
    source = work / f"{stem}.fens"
    target = work / f"{stem}.children.jsonl"
    source.write_text("".join(f"{fen}\n" for fen in fens), encoding="utf-8")
    run_checked([jass, "--dump-children", str(source), str(target)])
    rows = [json.loads(line) for line in target.read_text(encoding="utf-8").splitlines()]
    if len(rows) != len(fens) or any(not isinstance(row, list) for row in rows):
        raise RuntimeError("dump-children lost line alignment")
    return rows


def oracle_records(
    jass: str,
    fens: list[str],
    work: Path,
    stem: str,
    depth: int,
    egdb: str | None,
    cache_mb: int,
) -> list[bytes]:
    if not fens:
        return []
    source = work / f"{stem}.in.jnnw"
    target = work / f"{stem}.out.jnnw"
    write_jnnw(source, [fen_to_record(fen) for fen in fens])
    command = [jass, "--deep-relabel", str(source), str(target), str(depth)]
    if egdb:
        command += ["--egdb", egdb]
    command += ["--cache-mb", str(cache_mb)]
    run_checked(command, timeout=max(300, len(fens) * 30 + 120))
    records = read_jnnw(target)
    if len(records) != len(fens):
        raise RuntimeError("oracle output lost record alignment")
    for fen, record in zip(fens, records):
        if board_key(fen) != record[:33]:
            raise RuntimeError("oracle changed/reordered a position")
    return records


def load_jsonl(path: Path) -> list[dict]:
    opener = gzip.open if path.suffix == ".gz" else open
    with opener(path, "rt", encoding="utf-8") as handle:
        rows = [json.loads(line) for line in handle if line.strip()]
    if any(not isinstance(row, dict) for row in rows):
        raise ValueError("trajectory JSONL must contain objects")
    return rows


@dataclass
class Step:
    source_game_id: str
    trajectory_hash: str
    parent_fen: str
    played_move: str
    played_child_fen: str
    parent_wdl: int
    child_parent_pov: int


def steps_from_trajectories(
    rows: list[dict],
    *,
    jass: str,
    work: Path,
    depth: int,
    egdb: str | None,
    cache_mb: int,
) -> tuple[list[Step], int]:
    unique: dict[bytes, str] = {}
    for row in rows:
        for fen in row.get("fens", []):
            unique.setdefault(board_key(fen), fen)
    ordered = list(unique.values())
    relabelled = oracle_records(jass, ordered, work, "trajectory-oracle", depth, egdb, cache_mb)
    labels = {board_key(fen): signed_wdl(rec) for fen, rec in zip(ordered, relabelled)}
    steps: list[Step] = []
    for row in rows:
        fens = list(row.get("fens") or [])
        moves = list(row.get("moves") or [])
        limit = min(len(moves), max(0, len(fens) - 1))
        gid = str(row.get("source_game_id") or hashlib.sha256(
            str(row.get("opening", "")).encode()).hexdigest()[:24])
        trajectory_hash = str(row.get("trajectory_hash") or "")
        for index in range(limit):
            parent, child = fens[index], fens[index + 1]
            steps.append(Step(
                source_game_id=gid,
                trajectory_hash=trajectory_hash,
                parent_fen=parent,
                played_move=str(moves[index]),
                played_child_fen=child,
                parent_wdl=labels[board_key(parent)],
                child_parent_pov=-labels[board_key(child)],
            ))
    return steps, len(rows)


def steps_from_historical(
    gen_path: Path,
    oracle_path: Path,
    *,
    jass: str,
    work: Path,
) -> tuple[list[Step], int]:
    generated, oracle = read_jnnw(gen_path), read_jnnw(oracle_path)
    if len(generated) != len(oracle):
        raise ValueError("historical gen/oracle counts differ")
    for left, right in zip(generated, oracle):
        if left[:33] != right[:33]:
            raise ValueError("historical gen/oracle positions are not aligned")
    fens = [record_to_fen(record) for record in generated]
    children = dump_children(jass, fens, work, "historical")
    steps: list[Step] = []
    game_no = 0
    game_start = 0
    for index in range(max(0, len(fens) - 1)):
        next_key = generated[index + 1][:33]
        matches = [child for child in children[index]
                   if board_key(child["fen"]) == next_key]
        if len(matches) != 1:
            game_no += 1
            game_start = index + 1
            continue
        start_hash = hashlib.sha256(generated[game_start][:33]).hexdigest()[:16]
        gid = f"legacy-{game_no:06d}-{start_hash}"
        trajectory_hash = hashlib.sha256(
            generated[index][:33] + generated[index + 1][:33]
        ).hexdigest()
        steps.append(Step(
            source_game_id=gid,
            trajectory_hash=trajectory_hash,
            parent_fen=fens[index],
            played_move=str(matches[0]["move"]),
            played_child_fen=fens[index + 1],
            parent_wdl=signed_wdl(oracle[index]),
            child_parent_pov=-signed_wdl(oracle[index + 1]),
        ))
    return steps, game_no + (1 if fens else 0)


def endpoints(move: str) -> tuple[int, int]:
    match = MOVE_RE.match(move)
    if not match:
        raise ValueError(f"unsupported teacher move: {move!r}")
    return int(match.group(1)), int(match.group(2))


def split_name(game_id: str, holdout_mod: int) -> str:
    bucket = int(hashlib.sha256(game_id.encode()).hexdigest(), 16) % holdout_mod
    return "holdout" if bucket == 0 else "train"


def piece_count(fen: str) -> int:
    record = fen_to_record(fen)
    return sum(struct.unpack_from("<4Q", record, 0)[i].bit_count() for i in range(4))


def build_teacher(
    steps: list[Step],
    *,
    jass: str,
    work: Path,
    out_dir: Path,
    probe_tour: str,
    engine_sha: str,
    weights_sha: str,
    depth: int,
    egdb: str | None,
    cache_mb: int,
    holdout_mod: int,
    max_siblings_per_parent: int,
    games_inspected: int,
) -> dict:
    # Unit = decision parent.  Dedupe before the expensive sibling oracle.
    causal: list[Step] = []
    seen: set[bytes] = set()
    for step in steps:
        key = board_key(step.parent_fen)
        if step.parent_wdl != 1 or step.child_parent_pov not in (0, -1) or key in seen:
            continue
        seen.add(key)
        causal.append(step)

    child_rows = dump_children(jass, [step.parent_fen for step in causal], work, "causal")
    eligible: list[tuple[Step, list[dict]]] = []
    sibling_fens: list[str] = []
    sibling_owner: list[int] = []
    for step, children in zip(causal, child_rows):
        # Captures are deliberately excluded: the existing rank path and its
        # explicit two-byte move contract are quiet-decision only.
        if len(children) < 2 or any(bool(child.get("capture")) for child in children):
            continue
        played = [child for child in children
                  if board_key(child["fen"]) == board_key(step.played_child_fen)]
        if len(played) != 1:
            continue
        siblings = [child for child in children if child is not played[0]]
        if not siblings:
            continue
        owner = len(eligible)
        eligible.append((step, siblings))
        for child in siblings:
            sibling_fens.append(child["fen"])
            sibling_owner.append(owner)

    sibling_records = oracle_records(
        jass, sibling_fens, work, "sibling-oracle", depth, egdb, cache_mb
    )
    certified: list[list[dict]] = [[] for _ in eligible]
    for owner, child, record in zip(sibling_owner, sibling_fens, sibling_records):
        # Recover the matching move in the owner's small legal list.
        match = next(item for item in eligible[owner][1]
                     if board_key(item["fen"]) == board_key(child))
        wdl_stm = signed_wdl(record)
        certified[owner].append({
            "move": match["move"],
            "fen": child,
            "oracle_stm": wdl_stm,
            "oracle_parent_pov": -wdl_stm,
        })

    buffers = {
        split: {"parents": [], "good": bytearray(), "bad": bytearray(),
                "b1": [], "b2": [], "events": []}
        for split in ("train", "holdout")
    }
    all_events: list[dict] = []
    for (step, _), siblings in zip(eligible, certified):
        winning = sorted(
            (item for item in siblings if item["oracle_parent_pov"] == 1),
            key=lambda item: (item["move"], item["fen"]),
        )
        if not winning:
            continue
        good = winning[0]
        split = split_name(step.source_game_id, holdout_mod)
        parent_id = hashlib.sha256(board_key(step.parent_fen)).hexdigest()
        event_type = "WIN_TO_DRAW" if step.child_parent_pov == 0 else "WIN_TO_LOSS"
        ordered_siblings = sorted(siblings, key=lambda item: (item["move"], item["fen"]))
        capped_siblings = ordered_siblings[:max_siblings_per_parent]
        if good not in capped_siblings:
            # B1 must always receive the counterfactual that defines the B2/B3
            # pair, even when the per-parent inventory cap is tight.
            capped_siblings[-1] = good
        event = {
            "schema": 1,
            "probe_tour": probe_tour,
            "source_game_id": step.source_game_id,
            "split": split,
            "parent_id": parent_id,
            "parent_hash": parent_id,
            "parent_fen": step.parent_fen,
            "parent_oracle": "WIN",
            "played_move": step.played_move,
            "played_child_fen": step.played_child_fen,
            "played_child_oracle": "DRAW" if step.child_parent_pov == 0 else "LOSS",
            "event_type": event_type,
            "good_move": good["move"],
            "good_child_fen": good["fen"],
            "good_child_oracle": "WIN",
            "siblings": capped_siblings,
            "oracle_provenance": {
                "tier": f"DEEP_D{depth}" + ("_EGDB_AVAILABLE" if egdb else ""),
                "pieces": piece_count(step.parent_fen),
            },
            "engine_sha": engine_sha,
            "weights_sha": weights_sha,
            "trajectory_hash": step.trajectory_hash,
        }
        all_events.append(event)
        target = buffers[split]
        target["events"].append(event)
        target["parents"].append(fen_to_record(step.parent_fen))
        gf, gt = endpoints(good["move"])
        bf, bt = endpoints(step.played_move)
        target["good"] += bytes([gf, gt])
        target["bad"] += bytes([bf, bt])
        # B1 uses ordinary sibling WDL in each child's own STM POV.
        target["b1"].extend(
            fen_to_record(item["fen"], item["oracle_stm"])
            for item in capped_siblings
        )
        # B2: exactly the same selected oracle pair that B3 will consume.
        target["b2"].append(fen_to_record(good["fen"], -1))
        target["b2"].append(fen_to_record(step.played_child_fen, -step.child_parent_pov))

    out_dir.mkdir(parents=True, exist_ok=True)
    with (out_dir / "events.jsonl").open("w", encoding="utf-8") as handle:
        for event in all_events:
            handle.write(json.dumps(event, sort_keys=True, ensure_ascii=False) + "\n")
    split_counts = {}
    for split, data in buffers.items():
        root = out_dir / split
        root.mkdir(parents=True, exist_ok=True)
        write_jnnw(root / "parents.jnnw", data["parents"])
        (root / "good_moves.bin").write_bytes(data["good"])
        (root / "bad_moves.bin").write_bytes(data["bad"])
        write_jnnw(root / "b1_siblings.jnnw", data["b1"])
        write_jnnw(root / "b2_pairs.jnnw", data["b2"])
        with (root / "events.jsonl").open("w", encoding="utf-8") as handle:
            for event in data["events"]:
                handle.write(json.dumps(event, sort_keys=True, ensure_ascii=False) + "\n")
        split_counts[split] = len(data["events"])

    win_to_draw = sum(event["event_type"] == "WIN_TO_DRAW" for event in all_events)
    win_to_loss = len(all_events) - win_to_draw
    summary = {
        "schema": 1,
        "probe_tour": probe_tour,
        "engine_sha": engine_sha,
        "weights_sha": weights_sha,
        "games_inspected": games_inspected,
        "transitions_inspected": len(steps),
        "causal_parents_before_sibling_oracle": len(causal),
        "teacher_parents": len(all_events),
        "win_to_draw": win_to_draw,
        "win_to_loss": win_to_loss,
        "split_counts": split_counts,
        "holdout_mod": holdout_mod,
        "max_siblings_per_parent": max_siblings_per_parent,
        "b2_b3_alignment": {
            "parents": len(all_events),
            "pairs": len(all_events),
            "contract": "same parents/good_moves/bad_moves/split",
        },
    }
    (out_dir / "summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    return summary


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    source = parser.add_mutually_exclusive_group(required=True)
    source.add_argument("--trajectories", type=Path)
    source.add_argument("--gen", type=Path)
    parser.add_argument("--oracle", type=Path,
                        help="aligned historical deep.jnnw; required with --gen")
    parser.add_argument("--jass", required=True)
    parser.add_argument("--probe-tour", required=True)
    parser.add_argument("--out-dir", type=Path, required=True)
    parser.add_argument("--work-dir", type=Path, required=True)
    parser.add_argument("--oracle-depth", type=int, default=14)
    parser.add_argument("--egdb")
    parser.add_argument("--cache-mb", type=int, default=384)
    parser.add_argument("--holdout-mod", type=int, default=5)
    parser.add_argument("--max-siblings-per-parent", type=int, default=4)
    parser.add_argument("--engine-sha", default="...")
    parser.add_argument("--weights-sha", default="...")
    args = parser.parse_args(argv)
    if args.gen and not args.oracle:
        parser.error("--oracle is required with --gen")
    if args.holdout_mod < 2:
        parser.error("--holdout-mod must be >= 2")
    if args.max_siblings_per_parent < 1:
        parser.error("--max-siblings-per-parent must be >= 1")
    args.work_dir.mkdir(parents=True, exist_ok=True)

    if args.trajectories:
        rows = load_jsonl(args.trajectories)
        steps, games = steps_from_trajectories(
            rows,
            jass=args.jass,
            work=args.work_dir,
            depth=args.oracle_depth,
            egdb=args.egdb,
            cache_mb=args.cache_mb,
        )
    else:
        steps, games = steps_from_historical(
            args.gen,
            args.oracle,
            jass=args.jass,
            work=args.work_dir,
        )
    summary = build_teacher(
        steps,
        jass=args.jass,
        work=args.work_dir,
        out_dir=args.out_dir,
        probe_tour=args.probe_tour,
        engine_sha=args.engine_sha,
        weights_sha=args.weights_sha,
        depth=args.oracle_depth,
        egdb=args.egdb,
        cache_mb=args.cache_mb,
        holdout_mod=args.holdout_mod,
        max_siblings_per_parent=args.max_siblings_per_parent,
        games_inspected=games,
    )
    print(json.dumps(summary, sort_keys=True))
    return 0 if summary["teacher_parents"] > 0 else 3


if __name__ == "__main__":
    sys.exit(main())
