#!/usr/bin/env python3
"""Generate the preregistered Joint T+D Q1 teacher from the audited DSSD teacher.

The only scientific delta is the frozen Q1 diagnostic budget: 1,000 nodes
instead of the DSSD/M5 5,000-node diagnostic. The 50k screen, 200k target,
search implementation, terminal/TB precedence, parent POV and all engine
semantics remain source-identical. Output column names are relabelled q1000 so
that the terminal Q1 readout cannot accidentally consume the old q5k field.
"""
from __future__ import annotations

import argparse
from pathlib import Path

BUDGET_OLD = "constexpr std::uint64_t CHEAP_BUDGET = 5'000;"
BUDGET_NEW = "constexpr std::uint64_t CHEAP_BUDGET = 1'000;"

RENAMES = {
    "q5k_parent": "q1000_parent",
    "nodes5k": "nodes1000",
    "completed_depth5k": "completed_depth1000",
    "effective_depth5k": "effective_depth1000",
    "aborted5k": "aborted1000",
    "stop5k": "stop1000",
    "elapsed_us5k": "elapsed_us1000",
    "pv5k_enters_egdb": "pv1000_enters_egdb",
}

PREFIX = '''// Generated by jobs/tools/joint_td_q1_teacher_source.py. Do not edit.\n#include "pattern_jass_bridge.hpp"\n#include "scan_eval.hpp"\n#define load_pattern_jass_network load_eval_network\n'''
SUFFIX = '''\n#undef load_pattern_jass_network\n'''


def render(source: str) -> str:
    if source.count(BUDGET_OLD) != 1:
        raise ValueError(f"expected exactly one frozen DSSD cheap budget, got {source.count(BUDGET_OLD)}")
    out = source.replace(BUDGET_OLD, BUDGET_NEW, 1)
    for old, new in RENAMES.items():
        n = out.count(old)
        if n < 1:
            raise ValueError(f"missing audited output token {old!r}")
        out = out.replace(old, new)
    if BUDGET_OLD in out or "q5k_parent" in out:
        raise ValueError("old Q5k scientific contract survived Q1 rendering")
    if BUDGET_NEW not in out or "q1000_parent" not in out:
        raise ValueError("Q1 q1000 contract was not rendered")
    return PREFIX + out + SUFFIX


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, default=Path("src/deep_sibling_teacher.cpp"))
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    text = args.source.read_text(encoding="utf-8")
    rendered = render(text)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
