#!/usr/bin/env python3
"""Generate the preregistered Joint T+D Q1 teacher from the audited DSSD teacher.

Q1 changes only mechanics explicitly frozen by its preregistration relative to
the audited DSSD teacher source: diagnostic budget 1,000 nodes (not 5,000),
q1000 output naming, and a genuinely fresh Engine object for every sibling and
every budget. The 50k screen, 200k target, search implementation, terminal/TB
precedence, parent POV and all other semantics remain inherited verbatim.
"""
from __future__ import annotations

import argparse
from pathlib import Path

BUDGET_OLD = "constexpr std::uint64_t CHEAP_BUDGET = 5'000;"
BUDGET_NEW = "constexpr std::uint64_t CHEAP_BUDGET = 1'000;"
ENGINE_DECL = "    Engine engine(tt_mb);\n    engine.use_book(false);\n"
SEARCH_SIG_OLD = "SearchObs run_fresh_search(Engine& engine,\n                           const Position& child,"
SEARCH_SIG_NEW = "SearchObs run_fresh_search(std::size_t tt_mb,\n                           const Position& child,"
SEARCH_BODY_OLD = "    engine.clear_tt();\n    engine.set_position(child);"
SEARCH_BODY_NEW = "    Engine engine(tt_mb);\n    engine.use_book(false);\n    engine.clear_tt();\n    engine.set_position(child);"
CALL_OLD = "run_fresh_search(engine, child,"
CALL_NEW = "run_fresh_search(tt_mb, child,"

RENAMES = {
    "q5k_parent": "q1000_parent",
    "nodes5k": "nodes1000",
    "completed_depth5k": "completed_depth1000",
    "effective_depth5k": "effective_depth1000",
    "aborted5k": "aborted1000",
    "stop5k": "stop1000",
    "elapsed_us5k": "elapsed_us1000",
    "pv5k_enters_egdb": "pv1000_enters_egdb",
}

PREFIX = '''// Generated by jobs/tools/joint_td_q1_teacher_source.py. Do not edit.\n#include "pattern_jass_bridge.hpp"\n#include "scan_eval.hpp"\n#define load_pattern_jass_network load_eval_network\n'''
SUFFIX = '''\n#undef load_pattern_jass_network\n'''


def replace_exact(text: str, old: str, new: str, count: int) -> str:
    n = text.count(old)
    if n != count:
        raise ValueError(f"expected {count} occurrences of {old!r}, got {n}")
    return text.replace(old, new)


def render(source: str) -> str:
    out = replace_exact(source, BUDGET_OLD, BUDGET_NEW, 1)
    out = replace_exact(out, SEARCH_SIG_OLD, SEARCH_SIG_NEW, 1)
    out = replace_exact(out, SEARCH_BODY_OLD, SEARCH_BODY_NEW, 1)
    out = replace_exact(out, ENGINE_DECL, "", 1)
    # Audited teacher performs exactly three searches per sibling: diagnostic,
    # stability screen and final target. Q1 keeps those three budgets unchanged
    # except diagnostic 5k->1k, but requires fresh Engine state for each one.
    out = replace_exact(out, CALL_OLD, CALL_NEW, 3)
    for old, new in RENAMES.items():
        n = out.count(old)
        if n < 1:
            raise ValueError(f"missing audited output token {old!r}")
        out = out.replace(old, new)
    if BUDGET_OLD in out or "q5k_parent" in out or CALL_OLD in out or ENGINE_DECL in out:
        raise ValueError("old Q5k/reused-Engine contract survived Q1 rendering")
    if BUDGET_NEW not in out or "q1000_parent" not in out:
        raise ValueError("Q1 q1000 contract was not rendered")
    if out.count("Engine engine(tt_mb);") != 1:
        # It must appear only inside run_fresh_search, which is invoked anew for
        # each of the three budgets on every sibling.
        raise ValueError("Q1 generated teacher does not isolate Engine lifecycle")
    return PREFIX + out + SUFFIX


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--source", type=Path, default=Path("src/deep_sibling_teacher.cpp"))
    ap.add_argument("--output", type=Path, required=True)
    args = ap.parse_args()
    text = args.source.read_text(encoding="utf-8")
    rendered = render(text)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
